AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance"
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small]
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0933f1385008d33c4 # Ubuntu, 24.04 LTS
Outputs:
  InstanceId:
    Value: !Ref MyEC2Instance
