AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket"
Parameters:
  BucketName:
    Type: String
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: repository
          Value: cloudformation-demo
Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
